language: ruby
install: bundle install
script:
  - bundle exec rake db:create
  - bundle exec rake db:schema:load
  - bundle exec rake spec
rvm:
  - 2.3.0
  - 2.4.0
  - 2.5.0
  - 2.6.0
env:
  - "RAILS_VERSION=5.0.0"
  - "RAILS_VERSION=5.1.0"
  - "RAILS_VERSION=5.2.0"
  - "RAILS_VERSION=6.0.0"
  - "RAILS_VERSION=6.1.0"
matrix:
  include:
    - rvm: 2.3.0
      env: "RAILS_VERSION=5.0.0"
    - rvm: 2.3.0
      env: "RAILS_VERSION=5.1.0"
    - rvm: 2.3.0
      env: "RAILS_VERSION=5.2.0"
    - rvm: 2.4.0
      env: "RAILS_VERSION=5.0.0"
    - rvm: 2.4.0
      env: "RAILS_VERSION=5.1.0"
    - rvm: 2.4.0
      env: "RAILS_VERSION=5.2.0"
    - rvm: 2.5.0
      env: "RAILS_VERSION=5.0.0"
    - rvm: 2.5.0
      env: "RAILS_VERSION=5.1.0"
    - rvm: 2.5.0
      env: "RAILS_VERSION=5.2.0"
    - rvm: 2.6.0
      env: "RAILS_VERSION=6.0.0"
    - rvm: 2.6.0
      env: "RAILS_VERSION=6.1.0"
